allowBuilds:
  '@parcel/watcher': true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.5
  vitest: 4.1.10
  vite-plus: ^0.2.5
minimumReleaseAgeExclude:
  - '@v-c/dropdown@1.0.3'
  - '@v-c/input@1.1.1'
  - '@v-c/mentions@1.1.1'
  - '@v-c/menu@1.2.2'
  - '@v-c/notification@2.0.2'
  - '@v-c/picker@1.2.1'
  - '@v-c/resize-observer@1.1.3'
  - '@v-c/select@1.1.4'
  - '@v-c/tooltip@1.0.4'
  - '@v-c/tour@1.1.1'
  - '@v-c/trigger@1.0.18'
  - '@v-c/util@1.0.20'
  - antdv-next@1.4.3
  - '@voidzero-dev/vite-plus-core@0.2.5'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.5'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.5'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.5'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.5'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.5'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.5'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.5'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.5'
  - vite-plus@0.2.5
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
